version: "3.8"

services:
  mongo:
    image: mongo:5
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test:
        [
          "CMD",
          "mongo",
          "-u",
          "root",
          "-p",
          "example",
          "--authenticationDatabase",
          "admin",
          "--eval",
          "db.adminCommand('ping')",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./
    container_name: backend
    working_dir: /app
    ports:
      - "4000:4000"
    depends_on:
      mongo:
        condition: service_healthy
