version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    command: ["npm", "run", "dev", "--", "--host","0.0.0.0"]